FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest  

WORKDIR /root/

# Bring over the built binary from the first step
COPY --from=builder /app/main .

# Expose the port your service uses (change 8080 if needed)
EXPOSE 8080

# Run the executable
CMD ["./main"]